/**
 * Generates the reference-table seed from the TypeScript content, which stays
 * the source of truth (the CMS is a later phase). progress.experience_id and
 * mastery.concept_slug are foreign keys into these tables, so nothing can be
 * recorded for a student until they are populated.
 *
 * Re-run after changing journeys/experiences/concepts:
 *   npx tsx scripts/gen-seed.ts > supabase/migrations/0003_seed_content.sql
 */
import { JOURNEYS } from '../src/content/journeys';
import { CONCEPTS } from '../src/content/concepts';
import { EXPERIENCES } from '../src/content/experiences';

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const out: string[] = [];

out.push('-- GENERATED by scripts/gen-seed.ts — do not edit by hand.');
out.push('-- Reference rows only: no student data, no lesson copy.');
out.push('-- Idempotent so it can be re-applied after content changes.');
out.push('');

out.push('insert into journeys (id, slug, title, short_title, order_index, color_token, est_minutes) values');
out.push(JOURNEYS.map((j) =>
  `  (${q(j.id)}, ${q(j.slug)}, ${q(j.title)}, ${q(j.shortTitle)}, ${j.orderIndex}, ${q(j.colorToken)}, ${j.estimatedMinutes})`
).join(',\n') + '\non conflict (id) do update set');
out.push('  slug=excluded.slug, title=excluded.title, short_title=excluded.short_title,');
out.push('  order_index=excluded.order_index, color_token=excluded.color_token, est_minutes=excluded.est_minutes;');
out.push('');

out.push('insert into concepts (slug, title, is_core_concept) values');
out.push(CONCEPTS.map((c) =>
  `  (${q(c.slug)}, ${q(c.title)}, ${c.isCoreConcept})`
).join(',\n') + '\non conflict (slug) do update set');
out.push('  title=excluded.title, is_core_concept=excluded.is_core_concept;');
out.push('');

out.push('insert into experiences (id, journey_id, slug, title, mechanic_type, is_core, time_sensitive) values');
out.push(EXPERIENCES.map((e) =>
  `  (${q(e.id)}, ${q(e.journeyId)}, ${q(e.slug)}, ${q(e.title)}, ${q(e.mechanicType)}, ${e.isCore ?? true}, ${e.timeSensitive ?? false})`
).join(',\n') + '\non conflict (id) do update set');
out.push('  journey_id=excluded.journey_id, slug=excluded.slug, title=excluded.title,');
out.push('  mechanic_type=excluded.mechanic_type, is_core=excluded.is_core, time_sensitive=excluded.time_sensitive;');
out.push('');

out.push('insert into experience_concepts (experience_id, concept_slug) values');
const pairs: string[] = [];
for (const e of EXPERIENCES) for (const c of e.concepts) pairs.push(`  (${q(e.id)}, ${q(c)})`);
out.push(pairs.join(',\n') + '\non conflict do nothing;');

console.log(out.join('\n'));
