-- GENERATED by scripts/gen-seed.ts — do not edit by hand.
-- Reference rows only: no student data, no lesson copy.
-- Idempotent so it can be re-applied after content changes.

insert into journeys (id, slug, title, short_title, order_index, color_token, est_minutes) values
  ('j01', 'money-mindset', 'Money Mindset', 'Mindset', 1, 'n10', 4),
  ('j02', 'earning-income', 'Earning & Income', 'Earning', 2, 'n20', 4),
  ('j03', 'budgeting', 'Budgeting & Cash-Flow', 'Budgeting', 3, 'n50', 4),
  ('j04', 'banking-payments', 'Banking & Digital Payments', 'Banking', 4, 'n100', 4),
  ('j05', 'saving', 'Saving & Emergency Funds', 'Saving', 5, 'n200', 4),
  ('j06', 'credit-debt', 'Credit, Loans & Debt', 'Credit & Debt', 6, 'n2000', 4),
  ('j07', 'money-math', 'The Math Behind Money', 'Money Math', 7, 'n500', 4),
  ('j08', 'investing-basics', 'Investing Basics', 'Investing', 8, 'n10', 4),
  ('j09', 'destinations', 'Where Can Your Money Actually Go?', 'Destinations', 9, 'n50', 4),
  ('j10', 'planning', 'Planning Your Money Life', 'Planning', 10, 'n100', 4),
  ('j11', 'final-challenge', 'Run a Financial Life', 'Final', 11, 'n200', 4)
on conflict (id) do update set
  slug=excluded.slug, title=excluded.title, short_title=excluded.short_title,
  order_index=excluded.order_index, color_token=excluded.color_token, est_minutes=excluded.est_minutes;

insert into concepts (slug, title, is_core_concept) values
  ('opportunity-cost', 'Opportunity cost', true),
  ('delayed-gratification', 'Delayed gratification', true),
  ('needs-vs-wants', 'Needs vs wants', true),
  ('active-income', 'Active income', true),
  ('passive-income', 'Passive income', true),
  ('gross-vs-net', 'Gross vs net pay', false),
  ('budgeting', 'Budgeting', true),
  ('cash-flow', 'Cash flow', true),
  ('fixed-vs-variable', 'Fixed vs variable costs', false),
  ('how-banks-work', 'How banks actually work', true),
  ('upi-safety', 'UPI and payment safety', true),
  ('account-types', 'Account types', false),
  ('emergency-fund', 'Emergency fund', true),
  ('saving-vs-investing', 'Saving vs investing', true),
  ('principal', 'Principal', true),
  ('interest', 'Interest', true),
  ('emi-true-cost', 'What an EMI really costs', true),
  ('loan-tenure', 'Loan tenure', true),
  ('credit-score', 'Credit score', true),
  ('minimum-payment-trap', 'The minimum payment trap', true),
  ('compounding', 'Compounding', true),
  ('simple-vs-compound', 'Simple vs compound interest', true),
  ('inflation', 'Inflation', true),
  ('time-value', 'Time value of money', true),
  ('risk-return', 'Risk and return', true),
  ('diversification', 'Diversification', true),
  ('volatility', 'Volatility', false),
  ('sip', 'Systematic investing', false),
  ('liquidity', 'Liquidity', true),
  ('time-horizon', 'Matching money to time horizon', true),
  ('goal-setting', 'Financial goal setting', true),
  ('net-worth', 'Net worth', true),
  ('scam-red-flags', 'Scam red flags', true),
  ('guaranteed-returns', 'The "guaranteed returns" lie', true),
  ('phishing-otp', 'OTP and phishing fraud', true)
on conflict (slug) do update set
  title=excluded.title, is_core_concept=excluded.is_core_concept;

insert into experiences (id, journey_id, slug, title, mechanic_type, is_core, time_sensitive) values
  ('e01', 'j01', 'buy-it-now-or-wait', 'Buy It Now, or Wait?', 'choice-fastforward', true, false),
  ('e02', 'j02', 'two-ways-to-get-paid', 'Two Ways to Get Paid', 'compare-income', true, false),
  ('e03', 'j03', 'can-you-survive-the-month', 'What''s Wrong With This Budget?', 'find-problem', true, false),
  ('e04', 'j04', 'follow-the-500', 'Would You Approve This?', 'payment-decisions', true, false),
  ('e05', 'j05', 'the-rainy-day-test', 'The Rainy Day Test', 'parallel-shock', true, false),
  ('e06', 'j06', 'what-does-this-loan-really-cost', 'What Does This Loan Really Cost?', 'emi-slider', true, false),
  ('e07', 'j07', 'watch-10000-grow', 'Watch ₹10,000 Grow', 'compound-curve', true, true),
  ('e08', 'j08', 'pick-your-risk', 'Pick Your Risk', 'allocate-portfolio', true, false),
  ('e09', 'j09', 'match-the-goal', 'Match the Goal', 'match-goal', true, false),
  ('e10', 'j10', 'your-money-map', 'Your Money Map', 'goal-planner', true, false),
  ('e11', 'j11', 'final-challenge', 'Run a Financial Life', 'final-challenge', true, false)
on conflict (id) do update set
  journey_id=excluded.journey_id, slug=excluded.slug, title=excluded.title,
  mechanic_type=excluded.mechanic_type, is_core=excluded.is_core, time_sensitive=excluded.time_sensitive;

insert into experience_concepts (experience_id, concept_slug) values
  ('e01', 'opportunity-cost'),
  ('e01', 'delayed-gratification'),
  ('e01', 'needs-vs-wants'),
  ('e02', 'active-income'),
  ('e02', 'passive-income'),
  ('e03', 'budgeting'),
  ('e03', 'cash-flow'),
  ('e03', 'needs-vs-wants'),
  ('e04', 'how-banks-work'),
  ('e04', 'upi-safety'),
  ('e05', 'emergency-fund'),
  ('e05', 'saving-vs-investing'),
  ('e06', 'principal'),
  ('e06', 'interest'),
  ('e06', 'emi-true-cost'),
  ('e06', 'loan-tenure'),
  ('e07', 'compounding'),
  ('e07', 'simple-vs-compound'),
  ('e07', 'inflation'),
  ('e07', 'time-value'),
  ('e08', 'risk-return'),
  ('e08', 'diversification'),
  ('e08', 'volatility'),
  ('e09', 'liquidity'),
  ('e09', 'time-horizon'),
  ('e09', 'saving-vs-investing'),
  ('e10', 'goal-setting'),
  ('e10', 'net-worth'),
  ('e10', 'time-horizon'),
  ('e11', 'budgeting'),
  ('e11', 'emergency-fund'),
  ('e11', 'net-worth')
on conflict do nothing;
